Repository Catch-team/Catch-BE, pull requests merged in 2024-04, with the labels that each got.

#22 [Feat] 1:1문의 게시판 기능 구현
  batch/gradlew.bat
  crm/build.gradle
  crm/gradlew
  crm/src/main/java/com/encore/thecatch/Post/dto/Request/UpdatePostReq.java
  crm/src/main/java/com/encore/thecatch/Post/dto/Response/ListPostRes.java
  crm/src/main/java/com/encore/thecatch/Post/service/PostService.java
  crm/src/main/java/com/encore/thecatch/admin/domain/Admin.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/s3/S3Config.java
  crm/src/main/java/com/encore/thecatch/common/s3/S3Service.java
  crm/src/main/java/com/encore/thecatch/common/util/S3UrlUtil.java
  crm/src/main/java/com/encore/thecatch/post/controller/PostController.java
  crm/src/main/java/com/encore/thecatch/post/dto/request/AddImageReq.java
  crm/src/main/java/com/encore/thecatch/post/dto/request/CreatePostReq.java
  crm/src/main/java/com/encore/thecatch/post/dto/request/UpdatePostReq.java
  crm/src/main/java/com/encore/thecatch/post/dto/response/AddImageRes.java
  crm/src/main/java/com/encore/thecatch/post/dto/response/CreatePostRes.java
  crm/src/main/java/com/encore/thecatch/post/dto/response/DetailPostRes.java
  crm/src/main/java/com/encore/thecatch/post/dto/response/MyPostListRes.java
  crm/src/main/java/com/encore/thecatch/post/dto/response/UpdatePostRes.java
  crm/src/main/java/com/encore/thecatch/post/entity/Active.java
  crm/src/main/java/com/encore/thecatch/post/entity/Image.java
  crm/src/main/java/com/encore/thecatch/post/entity/Post.java
  crm/src/main/java/com/encore/thecatch/post/entity/Status.java
  crm/src/main/java/com/encore/thecatch/post/repository/ImageRepository.java
  crm/src/main/java/com/encore/thecatch/post/repository/PostRepository.java
  crm/src/main/java/com/encore/thecatch/post/service/PostService.java
Labels: ✨feat

#25 [Feat] Admin 회원가입, 로그인 추가 및 이메일 관련 로직 추가
  crm/.gitignore
  crm/build.gradle
  crm/gradlew
  crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
  crm/src/main/java/com/encore/thecatch/admin/domain/Admin.java
  crm/src/main/java/com/encore/thecatch/admin/dto/request/AdminLoginDto.java
  crm/src/main/java/com/encore/thecatch/admin/dto/request/AdminSignUpDto.java
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminRepository.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/jwt/RefreshToken/RefreshToken.java
  crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
  crm/src/main/java/com/encore/thecatch/log/domain/AdminLog.java
  crm/src/main/java/com/encore/thecatch/log/domain/EmailLog.java
  crm/src/main/java/com/encore/thecatch/log/domain/LogType.java
  crm/src/main/java/com/encore/thecatch/log/domain/UserLog.java
  crm/src/main/java/com/encore/thecatch/log/repository/AdminLogRepository.java
  crm/src/main/java/com/encore/thecatch/log/repository/EmailLogRepository.java
  crm/src/main/java/com/encore/thecatch/log/repository/UserLogRepository.java
  crm/src/main/java/com/encore/thecatch/mail/EmailConfig.java
  crm/src/main/java/com/encore/thecatch/mail/Entity/EmailTask.java
  crm/src/main/java/com/encore/thecatch/mail/controller/EmailController.java
  crm/src/main/java/com/encore/thecatch/mail/dto/EmailCheckDto.java
  crm/src/main/java/com/encore/thecatch/mail/dto/EmailReqDto.java
  crm/src/main/java/com/encore/thecatch/mail/dto/GroupEmailReqDto.java
  crm/src/main/java/com/encore/thecatch/mail/repository/EmailTaskRepository.java
  crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
  crm/src/main/java/com/encore/thecatch/mail/service/RsData.java
  crm/src/main/java/com/encore/thecatch/post/service/PostService.java
  crm/src/main/java/com/encore/thecatch/user/controller/UserController.java
  crm/src/main/java/com/encore/thecatch/user/domain/User.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ✨feat

#27 [Docs] 회의록 추가
  .github/MeetingMinutes/3월 14일 회의.md
  .github/MeetingMinutes/3월 15일 회의.md
  .github/MeetingMinutes/3월 21일 회의.md
  .github/MeetingMinutes/3월 26일 회의.md
  .github/MeetingMinutes/4월 2일 회의.md
  .github/MeetingMinutes/4월 3일 회의.md
  crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
Labels: 📝docs

#30 Update README.md
  README.md
Labels: 📝docs

#31 [Fix] 로그인 인증 수정 (#19)
  crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
  crm/src/main/java/com/encore/thecatch/admin/domain/Admin.java
  crm/src/main/java/com/encore/thecatch/admin/dto/request/AdminLoginDto.java
  crm/src/main/java/com/encore/thecatch/admin/dto/request/AdminSignUpDto.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/jwt/JwtTokenProvider.java
  crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
  crm/src/main/java/com/encore/thecatch/log/domain/AdminLog.java
  crm/src/main/java/com/encore/thecatch/log/domain/EmailLog.java
  crm/src/main/java/com/encore/thecatch/log/repository/EmailLogRepository.java
  crm/src/main/java/com/encore/thecatch/mail/controller/EmailController.java
  crm/src/main/java/com/encore/thecatch/mail/dto/EmailCheckDto.java
  crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ✨feat

#33 [Fix] 마케터, CS담당자 계정 생성 관련 수정 (#19)
  crm/build.gradle
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/user/domain/Role.java
Labels: ✨feat

#34 [Feat]Coupon FE 연결중
  crm/src/main/java/com/encore/thecatch/coupon/dto/CouponResDto.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
Labels: ✨feat

#37 [Feat, Fix] 마스킹 구현 및 유저 엔티티 수정 #35
  crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
  crm/src/main/java/com/encore/thecatch/admin/domain/Admin.java
  crm/src/main/java/com/encore/thecatch/admin/dto/response/AdminDetailDto.java
  crm/src/main/java/com/encore/thecatch/admin/dto/response/AdminInfoDto.java
  crm/src/main/java/com/encore/thecatch/admin/dto/response/AdminSearchDto.java
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminRepository.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/RsData.java
  crm/src/main/java/com/encore/thecatch/common/util/MaskingUtil.java
  crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
  crm/src/main/java/com/encore/thecatch/user/domain/BirthDate.java
  crm/src/main/java/com/encore/thecatch/user/domain/Gender.java
  crm/src/main/java/com/encore/thecatch/user/domain/User.java
  crm/src/main/java/com/encore/thecatch/user/dto/request/UserSignUpDto.java
  crm/src/main/java/com/encore/thecatch/user/dto/response/UserInfoDto.java
Labels: ✨feat, ♻refactor

#39 [Fix] 관리자 계정 생성 #35
  crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
Labels: ✨feat

#40 [Feat] 통계데이터 조회 로직 구현 #36
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
  crm/src/main/java/com/encore/thecatch/comments/controller/CommentsController.java
  crm/src/main/java/com/encore/thecatch/comments/entity/Active.java
  crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
  crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
  crm/src/main/java/com/encore/thecatch/user/controller/UserController.java
  crm/src/main/java/com/encore/thecatch/user/dto/response/ChartAgeRes.java
  crm/src/main/java/com/encore/thecatch/user/dto/response/ChartGenderRes.java
  crm/src/main/java/com/encore/thecatch/user/dto/response/ChartGradeRes.java
  crm/src/main/java/com/encore/thecatch/user/repository/UserQueryRepository.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ✨feat

#38 [Feat] Coupon FE 연결
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/CouponFindResDto.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/CouponResDto.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/SearchCouponCondition.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
Labels: ✨feat

#48 고객리스트 로직 수정 (#47)
  crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
  crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
  crm/src/main/java/com/encore/thecatch/complaint/controller/ComplaintController.java
  crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
  crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintRepository.java
  crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
Labels: ♻refactor

#50 [Feat] 통계데이터 로직 추가 구현 (#49)
  crm/src/main/java/com/encore/thecatch/complaint/controller/ComplaintController.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/CountAllComplaintRes.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/CountStatusComplaintRes.java
  crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
  crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/CouponPublishCountRes.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/log/controller/LogController.java
  crm/src/main/java/com/encore/thecatch/log/dto/DayOfWeekLogin.java
  crm/src/main/java/com/encore/thecatch/log/dto/VisitTodayUserRes.java
  crm/src/main/java/com/encore/thecatch/log/repository/EmailLogQueryRepository.java
  crm/src/main/java/com/encore/thecatch/log/repository/UserLogQueryRepository.java
  crm/src/main/java/com/encore/thecatch/log/service/LogService.java
Labels: ✨feat

#54 [Fix] findByAdminId 수정
  crm/src/main/java/com/encore/thecatch/admin/dto/response/AdminInfoResDto.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
Labels: 🚨bug, ♻refactor

#55 [Feat] Push알림 구현
  .gitignore
  crm/build.gradle
  crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/firebase/FirebaseConfig.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/domain/Coupon.java
  crm/src/main/java/com/encore/thecatch/coupon/domain/CouponStatus.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/CouponFindResDto.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/CouponResDto.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/SearchCouponCondition.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
  crm/src/main/java/com/encore/thecatch/notification/FCMInitializer.java
  crm/src/main/java/com/encore/thecatch/notification/controller/NotificationApiController.java
  crm/src/main/java/com/encore/thecatch/notification/domain/Notification.java
  crm/src/main/java/com/encore/thecatch/notification/dto/NotificationRequestDto.java
  crm/src/main/java/com/encore/thecatch/notification/dto/PushTokenDto.java
  crm/src/main/java/com/encore/thecatch/notification/repository/NotificationRepository.java
  crm/src/main/java/com/encore/thecatch/notification/service/NotificationService.java
  crm/src/main/java/com/encore/thecatch/publishcoupon/repository/PublishCouponRepository.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/domain/ReceiveCoupon.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/dto/KafkaLimitedCoupon.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/dto/ReceiveCouponReqDto.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/kafka/CouponKafkaEventListener.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/repository/ReceiveCouponRepository.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/service/ReceiveCouponService.java
  crm/src/main/java/com/encore/thecatch/user/controller/UserController.java
  crm/src/main/java/com/encore/thecatch/user/domain/User.java
  crm/src/main/java/com/encore/thecatch/user/dto/response/UserFindResDto.java
  crm/src/main/java/com/encore/thecatch/user/dto/response/UserInfoDto.java
  crm/src/main/java/com/encore/thecatch/user/repository/UserRepository.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  publishcoupon/gradle/wrapper/gradle-wrapper.jar
  publishcoupon/gradle/wrapper/gradle-wrapper.properties
Labels: ✨feat

#56 [Feat] Push알림 구현 수정5
  crm/src/main/java/com/encore/thecatch/publishcoupon/kafka/CouponKafkaEventListener.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/kafka/CouponKafkaEventListener.java
Labels: ✨feat

#58 [Fix] 검색 로직 구현 및 수정
  crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
  crm/src/main/java/com/encore/thecatch/admin/domain/Admin.java
  crm/src/main/java/com/encore/thecatch/admin/dto/response/AdminSearchDto.java
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminRepository.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/comments/controller/CommentsController.java
  crm/src/main/java/com/encore/thecatch/comments/dto/request/CreateCommentsReq.java
  crm/src/main/java/com/encore/thecatch/comments/dto/response/CreateCommentsRes.java
  crm/src/main/java/com/encore/thecatch/comments/repository/CommentsRepository.java
  crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyComplaintRes.java
  crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/user/controller/UserController.java
  crm/src/main/java/com/encore/thecatch/user/domain/User.java
  crm/src/main/java/com/encore/thecatch/user/dto/request/UserSearchDto.java
  crm/src/main/java/com/encore/thecatch/user/dto/response/UserInfoDto.java
  crm/src/main/java/com/encore/thecatch/user/dto/response/UserListRes.java
  crm/src/main/java/com/encore/thecatch/user/repository/UserQueryRepository.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ♻refactor

#66 [Fix] 관리자페이지 문의 글 상세페이지 관련 로직 수정 (#64)
  crm/src/main/java/com/encore/thecatch/comments/dto/response/DetailCommentRes.java
  crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
Labels: ♻refactor

#67 쿠폰 마무리
  crm/.gitignore
  crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/firebase/FirebaseConfig.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/notification/FCMInitializer.java
  crm/src/main/java/com/encore/thecatch/notification/controller/NotificationApiController.java
  crm/src/main/java/com/encore/thecatch/notification/domain/Notification.java
  crm/src/main/java/com/encore/thecatch/notification/dto/PushTokenDto.java
  crm/src/main/java/com/encore/thecatch/notification/repository/NotificationRepository.java
  crm/src/main/java/com/encore/thecatch/notification/service/NotificationService.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/repository/ReceiveCouponRepository.java
  crm/src/main/java/com/encore/thecatch/user/controller/UserController.java
  crm/src/main/java/com/encore/thecatch/user/domain/User.java
  crm/src/main/java/com/encore/thecatch/user/dto/request/PublishUserDto.java
  crm/src/main/java/com/encore/thecatch/user/repository/UserRepository.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ✨feat

#70 미수신 알람
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/domain/Coupon.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/notification/controller/NotificationApiController.java
  crm/src/main/java/com/encore/thecatch/notification/controller/NotificationController.java
  crm/src/main/java/com/encore/thecatch/notification/dto/NotificationResDto.java
  crm/src/main/java/com/encore/thecatch/notification/repository/NotificationRepository.java
  crm/src/main/java/com/encore/thecatch/notification/service/NotificationService.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ✨feat

#71 [Feat] 이벤트 생성
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/firebase/FirebaseConfig.java
  crm/src/main/java/com/encore/thecatch/event/controller/EventController.java
  crm/src/main/java/com/encore/thecatch/event/domain/Event.java
  crm/src/main/java/com/encore/thecatch/event/dto/request/EventCreateDto.java
  crm/src/main/java/com/encore/thecatch/event/repository/EventRepository.java
  crm/src/main/java/com/encore/thecatch/event/service/EventService.java
  crm/src/main/java/com/encore/thecatch/log/domain/LogType.java
  crm/src/main/java/com/encore/thecatch/mail/controller/EmailController.java
  crm/src/main/java/com/encore/thecatch/mail/dto/EventEmailReqDto.java
  crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
Labels: ✨feat

#72 [fix] 쿠폰검색 로직 수정
  crm/src/main/java/com/encore/thecatch/common/firebase/FirebaseConfig.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
Labels: ♻refactor

#73 [fix] 검색 기능 로직 수정
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
  crm/src/main/java/com/encore/thecatch/user/repository/UserQueryRepository.java
Labels: ♻refactor

#75 [Feat] 이벤트 생성
  crm/.gitignore
  crm/build.gradle
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/firebase/FirebaseConfig.java
  crm/src/main/java/com/encore/thecatch/event/controller/EventController.java
  crm/src/main/java/com/encore/thecatch/event/dto/response/EventDetailDto.java
  crm/src/main/java/com/encore/thecatch/event/dto/response/EventInfoDto.java
  crm/src/main/java/com/encore/thecatch/event/dto/response/EventSearchDto.java
  crm/src/main/java/com/encore/thecatch/event/repository/EventQueryRepository.java
  crm/src/main/java/com/encore/thecatch/event/service/EventService.java
  crm/src/main/java/com/encore/thecatch/log/domain/LogType.java
  crm/src/main/java/com/encore/thecatch/user/repository/UserRepository.java
Labels: ✨feat

#76 [Fix] 마이페이지 게시글 조회 로직 수정
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyPageComplaints.java
  crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
Labels: ♻refactor

#78 [Fix] Query dsl support 제작 (#77)
  crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/querydsl/Querydsl4RepositorySupport.java
  crm/src/main/java/com/encore/thecatch/complaint/controller/ComplaintController.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/CountCategoryComplaint.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/CountStatusComplaintRes.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/ListComplaintRes.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyComplaints.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyPageComplaints.java
  crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
  crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
  crm/src/main/java/com/encore/thecatch/event/repository/EventQueryRepository.java
  crm/src/main/java/com/encore/thecatch/log/repository/EmailLogQueryRepository.java
  crm/src/main/java/com/encore/thecatch/log/repository/UserLogQueryRepository.java
  crm/src/main/java/com/encore/thecatch/user/dto/request/UserSignUpDto.java
  crm/src/main/java/com/encore/thecatch/user/repository/UserQueryRepository.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ♻refactor
