Repository Catch-team/Catch-BE, pull requests merged in 2024-05, with the labels that each got.

#81 [Fix] 엑세스 토큰, 리프레시 토큰 만료 됐을때 로직 수정
  crm/src/main/java/com/encore/thecatch/admin/domain/Admin.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/jwt/JwtTokenProvider.java
  crm/src/main/java/com/encore/thecatch/common/jwt/RefreshToken/RefreshToken.java
  crm/src/main/java/com/encore/thecatch/common/jwt/RefreshToken/RefreshTokenRepository.java
  crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
  crm/src/main/java/com/encore/thecatch/event/controller/EventController.java
  crm/src/main/java/com/encore/thecatch/event/dto/response/EventContentsDto.java
  crm/src/main/java/com/encore/thecatch/event/service/EventService.java
  crm/src/main/java/com/encore/thecatch/log/domain/EmailLog.java
  crm/src/main/java/com/encore/thecatch/log/repository/EmailLogRepository.java
  crm/src/main/java/com/encore/thecatch/mail/Entity/EmailTask.java
  crm/src/main/java/com/encore/thecatch/mail/controller/EmailController.java
  crm/src/main/java/com/encore/thecatch/mail/repository/EmailTaskRepository.java
  crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
  crm/src/main/java/com/encore/thecatch/notification/controller/NotificationController.java
  crm/src/main/java/com/encore/thecatch/notification/repository/NotificationRepository.java
  crm/src/main/java/com/encore/thecatch/notification/service/NotificationService.java
  crm/src/main/java/com/encore/thecatch/user/domain/User.java
  crm/src/main/java/com/encore/thecatch/user/dto/request/UserSignUpDto.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ♻refactor

#84 [fix] Q객체 오류 수정
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/event/service/EventService.java
  crm/src/main/java/com/encore/thecatch/log/service/LogService.java
  crm/src/main/java/com/encore/thecatch/user/dto/request/UserSignUpDto.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ♻refactor

#88 상태 수정 및 쿠폰 이메일 로그 추가
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/domain/Coupon.java
  crm/src/main/java/com/encore/thecatch/coupon/domain/CouponStatus.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/CouponReqDto.java
  crm/src/main/java/com/encore/thecatch/coupon/dto/CouponResDto.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/event/controller/EventController.java
  crm/src/main/java/com/encore/thecatch/event/domain/EventStatus.java
  crm/src/main/java/com/encore/thecatch/event/service/EventService.java
  crm/src/main/java/com/encore/thecatch/log/domain/CouponEmailLog.java
  crm/src/main/java/com/encore/thecatch/log/domain/LogType.java
  crm/src/main/java/com/encore/thecatch/log/repository/CouponEmailLogRepository.java
  crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
Labels: ✨feat

#91 [Feat] 슈퍼 계정 관련 로직 추가
  crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
  crm/src/main/java/com/encore/thecatch/common/jwt/JwtAuthFilter.java
  crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
  crm/src/main/java/com/encore/thecatch/mail/dto/CommentsEmailDto.java
  crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
  crm/src/main/resources/application-dev.yml
Labels: ✨feat

#93 배포 과정 추가
  .github/Image/Catch-아키텍처.png
  README.md
Labels: 📝docs

#94 쿠폰 차트 통계 로직 추가
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/common/s3/S3Service.java
  crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
  crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/log/controller/LogController.java
  crm/src/main/java/com/encore/thecatch/log/domain/LogType.java
  crm/src/main/java/com/encore/thecatch/log/repository/CouponEmailLogQueryRepository.java
  crm/src/main/java/com/encore/thecatch/log/service/LogService.java
  crm/src/main/java/com/encore/thecatch/receivecoupon/repository/ReceiveCouponQueryRepository.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ✨feat

#96 캠페인 차트 로직 구현
  crm/src/main/java/com/encore/thecatch/event/controller/EventController.java
  crm/src/main/java/com/encore/thecatch/event/repository/EventQueryRepository.java
  crm/src/main/java/com/encore/thecatch/event/service/EventService.java
  crm/src/main/java/com/encore/thecatch/log/controller/LogController.java
  crm/src/main/java/com/encore/thecatch/log/repository/EmailLogQueryRepository.java
  crm/src/main/java/com/encore/thecatch/log/service/LogService.java
Labels: ✨feat

#104 미수신 알람 기능
  crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/notification/controller/NotificationController.java
  crm/src/main/java/com/encore/thecatch/notification/domain/Notification.java
  crm/src/main/java/com/encore/thecatch/notification/dto/PushTokenDto.java
  crm/src/main/java/com/encore/thecatch/notification/repository/NotificationRepository.java
  crm/src/main/java/com/encore/thecatch/notification/service/NotificationService.java
  crm/src/main/java/com/encore/thecatch/user/controller/UserController.java
  crm/src/main/java/com/encore/thecatch/user/service/UserService.java
Labels: ✨feat

#105 캠페인 상태 수정
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/event/service/EventService.java
Labels: ✨feat

#108 문의글 카테고리 검색 추가
  crm/src/main/java/com/encore/thecatch/complaint/dto/request/SearchComplaintCondition.java
  crm/src/main/java/com/encore/thecatch/complaint/dto/response/ListComplaintRes.java
  crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
  crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
Labels: ✨feat

#109 쿠폰, 캠페인 삭제
  crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
  crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
  crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
  crm/src/main/java/com/encore/thecatch/event/service/EventService.java
Labels: ✨feat
